# Generated by Django 3.2.21 on 2023-09-06 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pizzas', models.ManyToManyField(related_name='orders', to='Pizzeria_App.Pizza')),
            ],
        ),
    ]
