# Generated by Django 3.2.21 on 2023-09-07 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria_App', '0002_auto_20230906_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
