# Generated by Django 3.2.21 on 2023-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria_App', '0003_pizza_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
